#!/usr/bin/env sh
GREEN='\033[0;32m' # green color seq
RED='\033[0;31m' # red color seq
STOP='\033[0m' # stop color seq
if [ "$(id -u)" -ne 0 ]; then
  printf "%b>>%b Error: tchroot must be run as root.\n" "$RED" "$STOP"
  exit 1
fi
mount --types proc /proc "$1"/proc
mount --rbind /sys "$1"/sys
mount --make-rslave "$1"/sys
mount --rbind /dev "$1"/dev
mount --make-rslave "$1"/dev
mount --bind /run "$1"/run
mount --make-slave "$1"/run
printf "%b>>%b Entering chroot %s...\n" "$GREEN" "$STOP" "$1"
chroot "$1" "$2"